### ISSUE TITLE
BundleException when installing

### ISSUE THREAD

**Issue by DxtrusJonesy** [echebbi/eclipse-discord-integration#82] opened 2020-06-04 18:53 UTC
## Bug description

Whenever I try and install this, i get a Framework error in the Eclipse error log.
Also, there is not section for Discord Rich Presence in the project properties window

```
org.osgi.framework.BundleException: Could not resolve module: fr.kazejiyu.discord.rpc.integration.ui.preferences [483]
  Unresolved requirement: Require-Bundle: fr.kazejiyu.discord.rpc.integration; bundle-version="0.8.3"
    -> Bundle-SymbolicName: fr.kazejiyu.discord.rpc.integration; bundle-version="1.2.0"; singleton:="true"
       fr.kazejiyu.discord.rpc.integration [481]
         Unresolved requirement: Require-Bundle: java-discord-rpc; bundle-version="[2.0.0,3.0.0)"

	at org.eclipse.osgi.container.Module.start(Module.java:462)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1844)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1837)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1778)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1742)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1664)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)
```

## Expected behavior
It installs and works

## How to reproduce

1. Install the thing
2. Go to the Eclipse Error Log
3. Witness the error

## Additional context

- **Plug-in version**: 1.2.0
- **Eclipse IDE version**: 2020-03 (4.15.0)

**Comment by echebbi** [comment] 2020-06-04 20:10
Thanks for reporting!

Can you make sure you've installed all features? From `Help` > `Install new software...`:

![image](https://user-images.githubusercontent.com/25926433/83804954-411b0980-a6af-11ea-92c0-9b601a17f114.png)

If no items is shown then everything has been installed properly. Otherwise please check remaining items and install them.

If the installation succeeds you should have the following plug-ins installed (`Help` > `About Eclipse IDE` > `Installation Details`):

![image](https://user-images.githubusercontent.com/25926433/83803666-437c6400-a6ad-11ea-9e68-935121202251.png)

According to your error message it looks like Eclipse IDE cannot find one of the plug-ins I provide (`java-discord-rpc`) but I can't reproduce the issue on Eclipse 4.15 (Java package). .

**Comment by DxtrusJonesy** [comment] 2020-06-05 14:31
I made sure when I installed it that everything was installed, however the issue persists.

**Comment by echebbi** [comment] 2020-06-05 17:47
I've just released a new `v1.2.1` where dependencies have been enforced; could you:

1. Uninstall all discord-related plug-ins
2. Install the new 1.2.1 version

(note: Eclipse IDE may rely too much on its cache; if the 1.2.1 version does not appear, from the *Install* window go to `Manage...`, select "Discord ..." and hit `Reload`)

You should then see:

![image](https://user-images.githubusercontent.com/25926433/83907013-e7751680-a764-11ea-969c-a9e0df49ddac.png)

![image](https://user-images.githubusercontent.com/25926433/83907065-04114e80-a765-11ea-9bdf-9c50079ac274.png)

If that doesn't fix the issue, could you please tell me:

 - whether Discord shows you're using Eclipse IDE as expected (first make sure that [it can detect Eclipse IDE as a game](https://github.com/echebbi/eclipse-discord-integration#discord-does-not-detect-eclipse-ide-as-a-game)),
 - whether *Discord Rich Presence for Eclipse IDE* shows up in `General` > `Startup and Shutdown`,
 - your OS,
 - the JRE used to launch Eclipse IDE,
 - the Eclipse package you're using (Java / C++ / whatever)
 - how you've installed Eclipse (zip file, snap, chocolatey, etc.),
 - whether you can reproduce the issue on other Eclipse installations.

It may help me reproduce the issue.

**Comment by DxtrusJonesy** [comment] 2020-06-05 19:47
- Discord doesnt detect eclipse on its own, as per the documentation I added it manually.
- Discord Rich Presence for Eclipse IDE does NOT show up in Startup and Shutdown.
- My OS is Windows 10 ver 1909
- Im using Eclipse Java
- I installed eclipse through its normal installation exe
- Havent tried any other eclipse versions, but I will now

**Comment by echebbi** [comment] 2020-06-05 21:25
> - Discord Rich Presence for Eclipse IDE does NOT show up in Startup and Shutdown

To be honest, if all the plug-ins are installed then that does not make any sense to me. I'm very puzzled as to why you face such an issue.

> Works fine with Eclipse PHP

I still cannot reproduce the issue, even with a fresh 2020-03 Java Eclipse installed through its installer. Just to be sure, have you tried to install the plug-in in a new Eclipse Java? If it works then that would mean that the problem is specific to your first Eclipse. In such a case, I would try to launch the IDE with the following command line:

> eclipse.exe -clean -clearPersistedState

It should [clear a lot of cached data](https://help.eclipse.org/2020-03/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Freference%2Fmisc%2Fruntime-options.html) (caution: also reset UI layout) which may help.

**Comment by echebbi** [comment] 2020-07-05 11:11
The problem cannot be reproduced so I'll consider that Eclipse IDE messed up during the installation and close the issue. Please comment/reopen if the same issue is faced again.

**Closed by echebbi** 2020-07-05 11:11 UTC
Labels: bug
